### ISSUE TITLE
failures when encrypting multiple files

### ISSUE THREAD

**Issue by modosc** [ConradIrwin/dotgpg#10]
we started seeing this recently - could be a ```ruby 2.2.2``` issue (we upgraded around a month ago) or something else underlying on osx i'm not sure. 

when encrypting multiple files in a directory via ```dotgpg edit *``` we inevitably get a failure:

    /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:462:in `encrypt_sign': Invalid signature scheme (GPGME::Error)
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/gpgme-2.0.8/lib/gpgme/crypto.rb:97:in `block in encrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:71:in `new'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/gpgme-2.0.8/lib/gpgme/crypto.rb:90:in `encrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:90:in `block in encrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:89:in `open'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:89:in `encrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:130:in `block in reencrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:127:in `each_pair'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/dir.rb:127:in `reencrypt'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/lib/dotgpg/cli.rb:118:in `edit'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/gems/dotgpg-0.6.0/bin/dotgpg:5:in `<top (required)>'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/bin/dotgpg:23:in `load'
	from /Users/jon/.rvm/gems/ruby-2.2.2@vouch_api/bin/dotgpg:23:in `<main>'

this seems to happen on random files while encrypting with random keys - there's nothing deterministic about the behavior. i haven't been able to repo it while encrypting a single file but it happens 100% when editing multiple files or when adding/removing keys.

**Comment by modosc** [comment]
tracked this down to the online backup agent we were using (https://www.backblaze.com/) . stopped using it, no more issues.

**Comment by ConradIrwin** [comment]
awesome, glad you tracked it down!
