### ISSUE TITLE
Grant Selective Access

### ISSUE THREAD

**Issue by delmendo** [ConradIrwin/dotgpg#12]
Is there a way to set it so that a user has encrypt/decrypt rights on only some files? So for example we encrypt our  production secrets for a sub set of developers. And our CI system has access to only the test settings?

**Comment by ConradIrwin** [comment]
@delmendo Right now the easiest way to do this is to maintain multiple dotgpg directories.

I have thought about implementing a system where you could use a structure like:


```
secrets/
— .gpg
    — a@b.com
    — b@b.com
— test/
     .gpgaccess
     secrets.gpg
— production/
    .gpgaccess
    secrets.gpg
```

But I honestly think it will be simpler and less error-prone to just copy the secret keys around if you need multiple levels of access.

**Comment by delmendo** [comment]
I'm not sure i understand.
right now it look slike dotgpg encrypts everything with all the keys that are on file. So if I add a key for our CI system it automatically gets added to .env.test.gpg but it also gets added to .env.production.gpg.

How can I share keys in a way that lets me have a key that is only on .env.test.gpg and not on .env.production.gpg?  If I encrypt it by hand with gpg - will dotgpg add them back when I add the next user?

**Comment by ConradIrwin** [comment]
You should set up the directoy layout like this:

```
test/
   — .dotgpg
       — ci-server@example.org
       — developer@example.org
  .env.gpg
production/
  — .dotgpg
       — deploy-script@example.org
       — developer@example.org
  .env.gpg

```

By running two dotgpg directories, one for production, and one for test, you can be sure that different people have access to different keys.
